### PR TITLE
Quick fix to let it compile in VS for .NET 5

### PR DESCRIPTION
**Pull request by WilbertOnGithub**
Maybe a starting point for issue #3 ?

The assembly this generates with a build in VS I can use successfully in my .NET 5 application.

### CODE REVIEW

**Comment by WilbertOnGithub** [comment]
Maybe suited for you @mangoyoga80 ?

**Comment by mangoyoga80** [comment]
@WilbertOnGithub I've not looked at the build process and how the NuGet package is created, but I would perhaps suggest replacing
`<TargetFramework>netstandard2.0<TargetFramework>` with `<TargetFrameworks>netstandard2.0;netstandard2.1;net50</TargetFrameworks>` to do multi-targeting for those with different needs than me?

**Comment by WilbertOnGithub** [comment]
I don't have that much experience in multi-targetting frameworks, but I'll give it a shot. Might take a couple of days before I have time (it currently works for me which solves my immediate need)

**Comment by mangoyoga80** [comment]
You can look at https://docs.microsoft.com/en-us/nuget/create-packages/multiple-target-frameworks-project-file
If the NuGet package is built using integrated features later versions project files, it should create the package with all targets

**Comment by Kromzem** [comment]
Hey :)

I know, some time has passed, but will this PR will be merged some day :D Because I'm targeting .net 7.0 right now and want to use this utility.

**Comment by Kromzem** [comment]
Closing this, because I fixed the issues with #6

**Pull request closed without merging**
